### PR TITLE
Add PHP 7.2 to .travis.yml

### PR DESCRIPTION
**Pull request by tenkoma**

### CODE REVIEW

**Comment by sizuhiko** [comment]
Please send PR to develop branch

**Comment by tenkoma** [comment]
Made a commit from develop branch.
But, Build is Failed...

**Comment by sizuhiko** [comment]
This is CakePHP issue.
Will be fix followings
https://github.com/nojimage/cakephp/commit/28075d82ec61fa3da242cdf2e3c9e9b6984eeed3

**Comment by sizuhiko** [comment]
I will restart job on travis after CakePHP updated,
and merge if tests success.

**Comment by tenkoma** [comment]
3.5.10 Released. https://github.com/cakephp/cakephp/releases/tag/3.5.10

Build succeeded on my branch.

https://travis-ci.org/tenkoma/cakephp-fabricate-adaptor/builds/322273811

**Comment by sizuhiko** [comment]
Now, Travis has a problem...
https://twitter.com/travisci/status/936308759185494016

**Pull request merged**
