### PR TITLE
update to CakePHP 4

### PR DESCRIPTION
**Pull request by kaz29**

### CODE REVIEW

**Comment by sizuhiko** [comment]
Please remove matrix before PHP7.2 from `.travis.yml`.
Maybe fix like after followings.

```yaml
php:
  - 7.2
  - 7.3
  - 7.4
```

**Comment by dakota** [comment]
Any chance of getting this merged?

**Comment by sizuhiko** [comment]
@dakota I will provide alpha version for CakePHP4, maybe later this month. Please wait.

**Comment by sizuhiko** [comment]
Please install this merged like followings:
`composer require sizuhiko/cake_fabricate:dev-cakephp4`

**Pull request merged**
